<?php
/**
 * Created by PhpStorm.
 * User: zhaolong
 * Date: 2019-08-14
 * Time: 22:35
 */

@include_once '/data/service_router.php';

return [
    'OCS_DOMIN'              => 'http://' . PSR_WEB_NEIGOU_OCS_DOMAIN,
    'CDN_BASE_URL_NO_SCHEME' => '//' . PSR_CDN_WEB_NEIGOU_WWW_DOMAIN,

    'SALYUT_DOMIN'      => PSR_WEB_NEIGOU_SALYUT,
    'SALYUT_SIGN'       => PSR_SALYUT_SIGN,
    'SALYUT_ORDER_SIGN' => PSR_SALYUT_ORDER_SIGN,
    'SALYUT_CDN'        => '//' . PSR_CDN_WEB_NEIGOU_SALYUT_DOMAIN,

    'MIS_DOMIN' => PSR_WEB_NEIGOU_MIS,
    'MIS_SIGN'  => PSR_MIS_SIGN,

    'STORE_DOMIN' => PSR_WEB_NEIGOU,
    'STORE_SIGN'  => PSR_STORE_SIGN,

    'SHOP_DOMIN'       => 'http://' . PSR_WEB_NEIGOU_SHOP_DOMAIN,
    'SHOP_SIGN'        => PSR_SHOP_SIGN,
    'SHOP_APPKEY'      => PSR_SHOP_APPKEY,
    'SHOP_APPSECRET'   => PSR_SHOP_APPSECRET,
    'SHOPNG_APPKEY'    => PSR_SHOPNG_APPKEY,
    'SHOPNG_APPSECRET' => PSR_SHOPNG_APPSECRET,


    'KEY_GEN_TOKEN'   => PSR_KEY_GEN_TOKEN,
    'JD_GOODS_CAT_ID' => PSR_JD_GOODS_CAT_ID,

    'OPENAPI_DOMIN'         => PSR_WEB_NEIGOU_OPENAPI_SAFE,
    'OPENAPI_CLIENT_ID'     => PSR_OPENAPI_CLIENT_ID,
    'OPENAPI_CLIENT_SECRET' => PSR_OPENAPI_CLIENT_SECRET,

    'IMPORT_FILE_WEB_DOMAIN' => PSR_WEB_NEIGOU_MIS.'/files/',

    'ESSEARCH_HOST'     => PSR_ESSEARCH_HOST,
    'ESSEARCH_PORT'     => PSR_ESSEARCH_NEW_PORT,
    'ESSEARCH_INDEX'    => PSR_ESSEARCH_INDEX,//灰度发布需要写死名字
    'ESSEARCH_TYPE'     => PSR_ESSEARCH_TYPE,
    'ESSEARCH_UP_INDEX' => PSR_ESSEARCH_UP_INDEX,//灰度发布需要写死名字
    'ESSEARCH_GOODS_KEYWORD_SEARCH_FILED' => PSR_ESSEARCH_GOODS_KEYWORD_SEARCH_FILED,//商品关键字搜索字段
    'ELK_DOMAIN'        => PSR_ELK_DOMAIN,

    'EINVOICE_HANGTIANJINSHUI_HOST'     => PSR_EINVOICE_HANGTIANJINSHUI_HOST,
    'EINVOICE_HANGTIANJINSHUI_PATH'     => PSR_EINVOICE_HANGTIANJINSHUI_PATH,
    'EINVOICE_HANGTIANJINSHUI_SALE_TAX' => PSR_EINVOICE_HANGTIANJINSHUI_SALE_TAX,
    'EINVOICE_HANGTIANJINSHUI_KPY'      => PSR_EINVOICE_HANGTIANJINSHUI_KPY,
    'EINVOICE_HANGTIANJINSHUI_SKY'      => PSR_EINVOICE_HANGTIANJINSHUI_SKY,
    'EINVOICE_HANGTIANJINSHUI_FHR'      => PSR_EINVOICE_HANGTIANJINSHUI_FHR,

    'OSS_ASSESS_KEY_ID'     => PSR_OSS_ASSESS_KEY_ID,
    'OSS_ACCESS_KEY_SECRET' => PSR_OSS_ACCESS_KEY_SECRET,
    'OSS_ENDPOINT'          => PSR_OSS_ENDPOINT,
    'OSS_BUCKET'            => PSR_OSS_BUCKET,
    'OSS_BUCKET_CDN'            => PSR_OSS_BUCKET_CDN,

    'BOS_AK'             => PSR_BOS_AK,
    'BOS_SK'             => PSR_BOS_SK,
    'BOS_ENDPOINT'       => PSR_BOS_ENDPOINT,
    'BOS_BUCKET'         => PSR_BOS_BUCKET,
    'CDN_WEB_NEIGOU_WWW' => PSR_CDN_WEB_NEIGOU_WWW,
    'IMAGE_DRIVER'       => PSR_IMAGE_DRIVER,

    'OBS_KEY'            => PSR_OBS_KEY,
    'OBS_SECRET'         => PSR_OBS_SECRET,
    'OBS_ENDPOINT'       => PSR_OBS_ENDPOINT,
    'OBS_BUCKET'         => PSR_OBS_BUCKET,

    'FU_YOU_ZHAO_KEY' => PSR_FU_YOU_ZHAO_KEY,
    'FU_YOU_ZHAO_SECRET' => PSR_FU_YOU_ZHAO_SECRET,
    'FU_YOU_ZHAO_ENDPOINT' => PSR_FU_YOU_ZHAO_ENDPOINT,
    'FU_YOU_ZHAO_BUCKET' => PSR_FU_YOU_ZHAO_BUCKET,

    'REDIS_THIRD_WEB_HOST' => PSR_REDIS_THIRD_WEB_HOST,
    'REDIS_THIRD_WEB_PORT' => PSR_REDIS_THIRD_WEB_PORT,
    'REDIS_THIRD_WEB_PWD'  => PSR_REDIS_THIRD_WEB_PWD,
    'ORDER_CREATE_VERSION' => 'v2',

    'PLATFORM_CODE' => PSR_PLATFORM_CODE,

    'JUYOU_MOVIE_DOMIN' => PSR_JUYOU_MOVIE_DOMIN,

    'ALL_PRODUCT_RULE' => PSR_ALL_PRODUCT_RULE,

    'MVP_DOMIN' => PSR_WEB_NEIGOU_MVP,
    'MVP_SIGN'  => PSR_OPENAPI_TOKEN_SIGN,

    'CLUB_DOMAIN' => PSR_WEB_DIANDI_CLUB,
    'CLUB_SIGN' => PSR_OPENAPI_SIGN,

    'KUAIDI100_DOMAIN' => 'http://www.kuaidi100.com',
    'KUAIDI100_KEY' => 'jwAYgGep2615',

    'KUAIDI100_STATUS_100' => 100,//顺丰需要手机号才能查找到物流信息，club_express.status数值

    'ALI_OCR_ASSESS_KEY_ID'     => PSR_ALI_OCR_ASSESS_KEY_ID,
    'ALI_OCR_ACCESS_KEY_SECRET' => PSR_ALI_OCR_ACCESS_KEY_SECRET,
    'ALI_OCR_ENDPOINT'          => PSR_ALI_OCR_ENDPOINT,

    'CHECK_ORDER_SUPPLIER_BN' => PSR_CHECK_ORDER_SUPPLIER_BN,
    'PRICE_CACHE_COMPANY' => PSR_PRICE_CACHE_COMPANY, // 价格缓存公司

    "REVERSE_GEOCODING_PLATFORM" => defined('PSR_REVERSE_GEOCODING_PLATFORM') ? PSR_REVERSE_GEOCODING_PLATFORM : 'baidu',//反向地理编码接口使用哪一个三方平台
    "ADDRESS_SUGGESTION_PLATFORM" => defined('PSR_ADDRESS_SUGGESTION_PLATFORM') ? PSR_ADDRESS_SUGGESTION_PLATFORM : 'baidu',//地址联想接口使用哪一个三方平台

    'JYFL_API_SALT' => PSR_CONFIG_JYFL_API_SALT,
    'JYFL_API_GATEWAY_DOMAIN' => PSR_API_GATEWAY_DOMAIN,

    //脱敏账号查询平台
    'DESENSITIZATION_ACCOUNT_PLATFORM' => defined('PSR_DESENSITIZATION_ACCOUNT_PLATFORM') ? PSR_DESENSITIZATION_ACCOUNT_PLATFORM : 'fulu',
];
