<?php
/**
 * Created by PhpStorm.
 * User: zhaolong
 * Date: 2019-08-14
 * Time: 22:35
 */

@include '/data/service_router.php';

return [
    'OCS_DOMIN'              => 'http://' . PSR_WEB_NEIGOU_OCS_DOMAIN,
    'CDN_BASE_URL_NO_SCHEME' => '//' . PSR_CDN_WEB_NEIGOU_WWW_DOMAIN,

    'SALYUT_DOMIN'      => PSR_WEB_NEIGOU_SALYUT,
    'SALYUT_SIGN'       => PSR_SALYUT_SIGN,
    'SALYUT_ORDER_SIGN' => PSR_SALYUT_ORDER_SIGN,
    'SALYUT_CDN'        => '//' . PSR_CDN_WEB_NEIGOU_SALYUT_DOMAIN,

    'MIS_DOMIN' => PSR_WEB_NEIGOU_MIS,
    'MIS_SIGN'  => PSR_MIS_SIGN,

    'STORE_DOMIN' => PSR_WEB_NEIGOU,
    'STORE_SIGN'  => PSR_STORE_SIGN,

    'SHOP_DOMIN'       => 'http://' . PSR_WEB_NEIGOU_SHOP_DOMAIN,
    'SHOP_SIGN'        => PSR_SHOP_SIGN,
    'SHOP_APPKEY'      => PSR_SHOP_APPKEY,
    'SHOP_APPSECRET'   => PSR_SHOP_APPSECRET,
    'SHOPNG_APPKEY'    => PSR_SHOPNG_APPKEY,
    'SHOPNG_APPSECRET' => PSR_SHOPNG_APPSECRET,


    'KEY_GEN_TOKEN'   => PSR_KEY_GEN_TOKEN,
    'JD_GOODS_CAT_ID' => PSR_JD_GOODS_CAT_ID,

    'OPENAPI_DOMIN'         => PSR_WEB_NEIGOU_OPENAPI_SAFE,
    'OPENAPI_CLIENT_ID'     => PSR_OPENAPI_CLIENT_ID,
    'OPENAPI_CLIENT_SECRET' => PSR_OPENAPI_CLIENT_SECRET,

    'ESSEARCH_HOST'     => PSR_ESSEARCH_HOST,
    'ESSEARCH_PORT'     => PSR_ESSEARCH_PORT,
    'ESSEARCH_INDEX'    => PSR_ESSEARCH_INDEX,
    'ESSEARCH_TYPE'     => PSR_ESSEARCH_TYPE,
    'ESSEARCH_UP_INDEX' => PSR_ESSEARCH_UP_INDEX,
    'ELK_DOMAIN'        => PSR_ELK_DOMAIN,

    'EINVOICE_HANGTIANJINSHUI_HOST'     => PSR_EINVOICE_HANGTIANJINSHUI_HOST,
    'EINVOICE_HANGTIANJINSHUI_PATH'     => PSR_EINVOICE_HANGTIANJINSHUI_PATH,
    'EINVOICE_HANGTIANJINSHUI_SALE_TAX' => PSR_EINVOICE_HANGTIANJINSHUI_SALE_TAX,
    'EINVOICE_HANGTIANJINSHUI_KPY'      => PSR_EINVOICE_HANGTIANJINSHUI_KPY,
    'EINVOICE_HANGTIANJINSHUI_SKY'      => PSR_EINVOICE_HANGTIANJINSHUI_SKY,
    'EINVOICE_HANGTIANJINSHUI_FHR'      => PSR_EINVOICE_HANGTIANJINSHUI_FHR,

    'OSS_ASSESS_KEY_ID'     => PSR_OSS_ASSESS_KEY_ID,
    'OSS_ACCESS_KEY_SECRET' => PSR_OSS_ACCESS_KEY_SECRET,
    'OSS_ENDPOINT'          => PSR_OSS_ENDPOINT,
    'OSS_BUCKET'            => PSR_OSS_BUCKET,

    'BOS_AK'                => PSR_BOS_AK,
    'BOS_SK'                => PSR_BOS_SK,
    'BOS_ENDPOINT'          => PSR_BOS_ENDPOINT,
    'BOS_BUCKET'            => PSR_BOS_BUCKET,
    'CDN_WEB_NEIGOU_WWW'            => PSR_CDN_WEB_NEIGOU_WWW,
    'IMAGE_DRIVER'            => PSR_IMAGE_DRIVER,

    'REDIS_THIRD_WEB_HOST' => PSR_REDIS_THIRD_WEB_HOST,
    'REDIS_THIRD_WEB_PORT' => PSR_REDIS_THIRD_WEB_PORT,
    'REDIS_THIRD_WEB_PWD'  => PSR_REDIS_THIRD_WEB_PWD,

    'PLATFORM_CODE' => PSR_PLATFORM_CODE,

    'JUYOU_MOVIE_DOMIN' => PSR_JUYOU_MOVIE_DOMIN,

    'ALL_PRODUCT_RULE' => PSR_ALL_PRODUCT_RULE,
    'ORDER_CREATE_VERSION' => 'v2',
];
